version: "3.4"
services:
  runner-ga-backend-access:
    image: gicom/ga-runner
    env_file: .env
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock